{% set version = "0.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clvalid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clValid_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clValid/clValid_{{ version }}.tar.gz
  sha256: 037da469891462021eb177f9c9e18caefa8532f08c68fb576fae1668a1f451a1

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-class
    - r-cluster
  run:
    - r-base
    - r-class
    - r-cluster

test:
  commands:
    - $R -e "library('clValid')"           # [not win]
    - "\"%R%\" -e \"library('clValid')\""  # [win]

about:
  home: http://guybrock.gpbrock.net/research
  license: LGPL-3-only
  summary: Statistical and biological validation of clustering results.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
