{% set version = "0.6-9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clvalid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clValid_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clValid/clValid_{{ version }}.tar.gz
  sha256: 0b205fdfa8b3d9856947c8db82b4b33d0babb8fee922d09517ae3bc6027cbb48

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-class
    - r-cluster
  run:
    - r-base
    - r-class
    - r-cluster

test:
  commands:
    - $R -e "library('clValid')"           # [not win]
    - "\"%R%\" -e \"library('clValid')\""  # [win]

about:
  home: http://guybrock.gpbrock.net/research
  license: LGPL-3
  summary: Statistical and biological validation of clustering results.
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
