travis:
  secure:
    BINSTAR_TOKEN: cHtuO2cIf9JAuznULP98vtoH9xTxWAtc+VmpU7kF/nCtAXciudhusQmy6eWvWLVBEilX6Za65bTa74Ky9HxRL/joPgFbbjj5mXdOLmv504sxLmVB1SWnZeGn1YAq1EIy2oO4Yrup3QnlNW5PdukPLUOTKonrnt+NmbVJv3jqPto9u9oHI1MjevdMefJRUyn2gOf/he1uXMk/fsF6/3vF9Ggc3JPqSPVjP4MsnVGKkuCzWiI23TvgAUhFY7WhfIONGcjCW1UwteeeOKOBqQj1HET9YtpCeOssRUs/8S2lno9PbYWZDqXBHBLZnZQlwFZDrriKMMpS+qcPaDE2GDXvpflwqbhWuoxmvayKfpjFovK92dQegjpUwh1h95GiRqbxCnZS6OiVclYgfrO8uSWilfmtzNBwTbr1hyBaSWl4tgL/Jz8zQiksr4zhujnTTAKmhuUu4inQs0BiSXDiJmbH51W8fIRExfrb3HyWM82BaqZJC3dY6rhLsfTqh44ga9DNqf12LsEs6VocjG1msSYOnru2njaRlPuhSlWYw6/4ApJFeg9pGBq+2n4iAwhc4x8pDF7QVQy4mCePdysM8hakGXLDRQCIcWTMkiwK3xmSnj+ipL4k2DQoZ8YNha/6QAEHx4i3GUXjQaWZ+pdNXXmJHNty8wqLxIy7hXaeQs7puHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
